name: CI/CD Portal Distribuido

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # 1. Primero, logueamos en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Ahora sí construimos y subimos la imagen
      - name: Build & push image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portal-distribuido:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          user: ec2-user                
          key_path: key.pem
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/portal-distribuido:latest
            docker stop portal || true
            docker rm portal   || true
            docker run -d --name portal -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/portal-distribuido:latest
